server:
  port: 8052

spring:
  application:
    name: SYSTEM

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8051/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  server:
    enable-self-preservation: false